### ISSUE TITLE
Dept of Environment use case & feedback 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terria-cube#1]
Jupyter notebook that provides a good worked example of what the Dept of the Environment and Energy would like to be able to do from a web UI. (without having to have an NCI log on and fly Jupyter NBs )
 
https://github.com/data-cube/agdc-v2-examples/blob/master/notebooks/05_interactive_time_series_with_time_slice_retrieval.ipynb
 
Using this as a starting point and adding the ability to view two thumbnails/image chips side by side (ie before and after a change event), would be ideal.

**Comment by AnaBelgun** [comment]
Specific terria issue here: https://github.com/TerriaJS/terriajs/issues/2557

**Comment by meh9** [comment]
Initial work on the UI functionality is being tracked in TerriaJS: TerriaJS/terriajs#2557.

**Comment by AnaBelgun** [comment]
Feedback 25 Oct 17

Landsat (or I imagine higher res) data
-          There is no way of seeing where and when data is available at the same time due to the zoom level required. It currently requires the viewer to be very zoomed in to see the data, which means there is no way to see if data is available in a particular location on the date selected other than attempting to pan around the continent. There needs to be some indication at a continental scale that data is available in a particular location, even if the area is just grey or something similar.
 
Splitter
-          The splitter function is excellent and the buttons to include the data on either side or both are really clear and obvious.
-          The text for the splitter button on the right of the screen would be better reading ‘split screen’ rather than ‘Toggle splitter control’.
-          It would be more intuitive if the button in the data box read ‘duplicate’ or ‘copy’ rather than split.
-          Feedback from others is that it is not easy to identify how to get different dates on each side of the split – not sure what to do about this, but perhaps calling the button in the data box duplicate will help.
 
Date picker
-          I really like the way the availability of data is displayed.
-          Skipping levels in the time picker even if there is only one option is confusing.
 
Timeline
-          The play functionality does not only show the actual dates, and so is not very effective for data like Landsat. Is there anyway of only including dates with data in a particular location?
-          The timeline does not have an indicator for when data is available – would be good to have a blue line on the timeline too.
 
Feature Information
-          Currently it is limited to only one expanded item which is automatically the top one, and if it is collapsed it expands again with the next click. All items need to be expanded and collapsed separately, and remember this choice.
-          It is currently only showing the top layer on each split rather than all displayed layers. It should include in the information which side it is displayed on, and only display once if it is on both.
For the solar satellite DNI and GHI it contains the value, however for the other layers I have looked at it only contains the xy. Would be useful to have the value for all layers.
 
Other
-          The https version doesn't work (CORS not enabled?)

**Comment by AnaBelgun** [comment]
Feedback 9 Nov 17
- There is an issue with the way the data is displayed – it is probably an issue with the underlying WMS. It does not contain data from only one date, despite indicating that this is data from the 27/01/2014. This appears in all the DEA layers I looked at
![terriacube pic1](https://user-images.githubusercontent.com/18452161/33158960-93efd29c-d062-11e7-9400-69423721b14f.jpg)

- LHTC high and low tide data was not loading correctly and had the wrong legend displayed (and these layers are now not available).  They were excellent while they worked to demonstrate the functionality. 

- Part way through the ability to slide the splitter disappeared, although a faint line could still be seen.

**Comment by rowanwins** [comment]
Closing - Nothing specifically actionable left
