### ISSUE TITLE
Develop REST interface for querying OGC datasets

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terria-cube#10]
Develop a metadata service to show information (e.g cloud presence, imagery presence etc) between selected dates (for a period of time). 
For example: what Landsat & Sentinel images are available at -32,146 between the date ranges August 2016 and December 2016:
o	API query parameters to include
-	Datasets to query
-	Date range
-	Location 
-	Metadata filters (eg percentage cloud cover)
o	API response to include 
-	Scene metadata (eg cloud cover)
-	URL of imagery in public bucket 
-	URL of associated map services

**Comment by rowanwins** [comment]
Not really an issue for this repo
