### ISSUE TITLE
Add GSKY WOfS and Geomedian layers 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terria-cube#11]
Surface Water and Marine / Water Observations from Space / Daily Water Observations
Data Providers / Digital Earth Australia / Daily Water Observations
GSKY Prod: http://gsky.nci.org.au/ows

Satellite Imagery / Continental Mosiacs / Annual Geometric Median (Landsat 8)
Satellite Imagery / Continental Mosiacs / Annual Geometric Median (Landsat 7)
Satellite Imagery / Continental Mosiacs / Annual Geometric Median (Landsat 5)
AWS new prod: https://geomedian.services.dea.ga.gov.au/

Add legends to WOfS: 
https://dea-public-data.s3.amazonaws.com/WOfS/WOFLs/v2.1.0/wofs-legend.svg
https://dea-public-data.s3.amazonaws.com/WOfS/WOFLs/v2.1.0/wofs-legend.png

**Comment by AnaBelgun** [comment]
Wait for GA to approve the publication

**Comment by rowanwins** [comment]
Pretty sure this is all done although the layers now live in different places
