### ISSUE TITLE
Add NEII Watercourse Discharge and Watercourse Levels

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terria-cube#14]
to make the new NEII feature available in the app, we need the 2 SOS water services

- http://neii.gov.au/viewer/#share=s-gQmdVjSpNjrB5z2UoSiOSkbxqPP
- http://neii.gov.au/viewer/#share=s-6SrvB4SiA5B6iNhKSfDb0UnSrQC

- it might be the case we need the HRS also (subset)

**Comment by AnaBelgun** [comment]
@reginapramesti please use the data link Kevin provided: https://github.com/TerriaJS/neii-viewer/blob/dea-demo/wwwroot/init/neii-demo.json

we might need the other two services, but will confirm with the client once this one is available in the catalogue

**Comment by reginapramesti** [comment]
I've added the layers, they're under the Water Regulations Data (BoM) category
