### ISSUE TITLE
Cloudfront - Chrome - error

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terria-cube#34]
Error message: ERR_SPDY_SERVER_REFUSED_STREAM 

to test: 
- go to terria cube app https://terria-cube.terria.io/
- go to DEA Production, Near real time, Sentinel 2A - https://terria-cube.terria.io/#share=s-2fAVZ6zGV3KUus4DPSyPonNERPK
- error message 
![image](https://user-images.githubusercontent.com/18452161/65005836-98702280-d944-11e9-8681-7d1f7b70a38e.png)
- and in console: 
![image](https://user-images.githubusercontent.com/18452161/65005854-aaea5c00-d944-11e9-9a8b-7157242c3cb6.png)

- terriaCube has Cloudfront
- same data services (https://nationalmap.gov.au/#share=s-7J1ezmmIYhns1wF1tWdlfrzN7Hr), from same stack (https://ows.services.dea.ga.gov.au), do not present this error in NationalMap, where Cloudfront is not applied (to double check because at the time of filing this bug, this is what the console had: 
![image](https://user-images.githubusercontent.com/18452161/65006083-67442200-d945-11e9-8b5a-3a0f21dbb144.png)

**Comment by rowanwins** [comment]
Currently with DEA for server-side investigation

**Comment by AnaBelgun** [comment]
While the DEA is investigating with Cloudfront, we need to review and merge this PR:
https://github.com/TerriaJS/terriajs/pull/3706

**Comment by AnaBelgun** [comment]
Will close this ticket for now, until there is something more specific for TerriaJSto fix.
