### ISSUE TITLE
TerriaCube - 14 May 2020 release for UX testing

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terria-cube#47]
Instead of combining the rollover of DEA maps process and UX testing when using TerriaCube prototype site, we will split the 2 processes in distinct releases: 1) TerriaCube - UX testing release and 2) TerriaCube - DEA MobX-ing release.

This ticket deals with 1). Separate ticket for 2) https://github.com/TerriaJS/terria-cube/issues/48

- [ ] set up a testing TerriaCube site 

- [x] populate catalogue with following datasets: 

**1) From http://maps.dea.ga.gov.au/** - all under the following groups, under a new **Australia** group 
![image](https://user-images.githubusercontent.com/18452161/81624647-0e784b00-943a-11ea-8d2f-fc68908f5937.png)

GSKY - https://gsky.nci.org.au/ows/dea
DEA GA - https://ows.dea.ga.gov.au/

**2) From http://de-africa.terria.io/** - all under the following groups, under a new **Africa** group 
![image](https://user-images.githubusercontent.com/18452161/81624842-93636480-943a-11ea-9ba2-f69293ac519a.png)

DEA GA - https://ows.digitalearth.africa/

- [x] Delta V2 https://github.com/terriajs/terriajs/issues/4145 and PR https://github.com/TerriaJS/terriajs/pull/4257

- [ ] Figure out help panel items order

- [ ] Onboarding: 
1) https://github.com/terriajs/terriajs/issues/4173 - Getting Started
2) https://github.com/terriajs/terriajs/issues/4180 - Welcome message
3) https://github.com/terriajs/terriajs/issues/4181 - Disclaimer
4) ~~https://github.com/terriajs/terriajs/issues/4183 - Tour~~
5) ~~https://github.com/TerriaJS/terriajs/pull/4165 - Misc UI tweaks~~

**Comment by soyarsauce** [comment]
There is a terria cube running on a slightly older mobx at http://terrace-terria-cube.map-builder.terria.io/

**Comment by soyarsauce** [comment]
- Crispy to put link into ticket @steve9164 
- 3 geojsons didn't convert - skipped them for now. 53 layers don't have the "ignore tile errors" property/trait, as we don't support ignoreTileErrors in mobx yet.
- Wing to fix "style dropdown" (offset caret)
- Put third, separate group for Delta after Africa + Australia
- Nanda to un-traitify discretetime on WMS. (If using objectArrayTraits for large arrays, very inefficient - no other parts of mobx do we use large arrays for this trait. But for now it's only the discretetime) - branch off as last resort if we can't do it cleanly.
- Alyce to guide user testing away from gsky services if required. @steve9164 to let Alyce know if anything is **really broken and just ignore it completely**
- @steve9164 put a URL for the terria-cube-mobx deployment, and we'll swap stacks to it as required
- Nanda/Alyce to ask Leo for good delta spots+dates
- Nanda to resolve legend-on-diff + PR comments, merge that, then in a separate PR, to fix the performance.
- Wing to resolve disclaimer + welcome message clash
- Alyce will be doing bulk of discussion guide on Friday+Monday. (What questions will be asked, what workflows and scenarios which will be run through). Anything that doesn't work in those workflows, Alyce will notify everyone
- Chrome is fastest, all of Chrome+Firefox+Edge+Safari should all work

Help panel order
- getting started (generic - it's an overview)
- satellite imagery (generic - copy the same panels from master, into the help panel)
- time series (ripped straight from NSW)
- compare (placeholder blank content for the generic-nav-to-come, ask users "what would be useful")


Other notes:
Have a small gap on first day of testing if we need to modify the catalog (they are s3 based so can swap out at runtime)
Generic video w/ splitter exists, based on old UI
Everything stable by Monday

**Comment by AnaBelgun** [comment]
https://tc-user-testing.terria.io/ set up and used for testing
