### ISSUE TITLE
Performance of Landsat data through NCI

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terria-cube#5]
Collation of user feedback: 
- There is no way of seeing where and when data is available at the same time due to the zoom level required. It currently requires the viewer to be very zoomed in to see the data, which means there is no way to see if data is available in a particular location on the date selected other than attempting to pan around the continent. There needs to be some indication at a continental scale that data is available in a particular location, even if the area is just grey or something similar

- There is an issue with the way the data is displayed – it is probably an issue with the underlying WMS. It does not contain data from only one date, despite indicating that this is data from the 27/01/2014. This appears in all the DEA layers I looked at
![terriacube pic1](https://user-images.githubusercontent.com/18452161/33159281-aa28f2f2-d065-11e7-8bfd-eefba146ce93.jpg)

- for the solar satellite DNI and GHI it contains the value, however for the other layers it only contains the XY

**Comment by AnaBelgun** [comment]
Suggestions for improvement: 
- As you zoom out, more and more data has to be loaded in order to generate the image tiles, so NCI had to put some arbitrary limits on when to stop generating tiles in order to return a response without the request timing out. NCI are actively working on improving the performance so that you can be further away and still see data. 

-  one solution may be to switch to using something like a Pixel Quality layer once you unzoom past a certain point so that you can at least show where there is data, which may show something instead of showing nothing

**Comment by rowanwins** [comment]
Closing - Nothing specifically actionable left
