### ISSUE TITLE
Digital Earth - TerriaCube catalogue

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terria-cube#67]
As discussed, could we please use this as the catalog for terria-cube?
https://raw.githubusercontent.com/GeoscienceAustralia/dea-config/master/dev/terria/terria-cube-v8.json
Our preference would be to use this catalog in place in Github so we can update it quickly and maintain it ourselves.

**Comment by AnaBelgun** [comment]
when / if we get a chance this sprint

**Comment by nf-s** [comment]
I have updated dev and test with new catalog

- https://terria-cube.test.saas.terria.io/

Can push to prod after GA confirmation

**Comment by AnaBelgun** [comment]
awesome, thank you @nf-s

**Comment by GypsyBojangles** [comment]
Looks good to me @nf-s and @AnaBelgun Thank you!

**Comment by nf-s** [comment]
I have pushed the new catalog to prod!
